# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# compile CXX with /Library/Developer/CommandLineTools/usr/bin/c++
CXX_DEFINES = -DCS211_TESTING

CXX_INCLUDES = -I"/Users/elliegoldsmith/Desktop/CS Projects/CS 211/final_project/src" -isystem "/Users/elliegoldsmith/Desktop/CS Projects/CS 211/final_project/.cs211/lib/catch/include" -isystem "/Users/elliegoldsmith/Desktop/CS Projects/CS 211/final_project/.cs211/lib/ge211/src/../include" -isystem "/Users/elliegoldsmith/Desktop/CS Projects/CS 211/final_project/cmake-build-debug/.cs211/lib/ge211/src/../include" -isystem /opt/homebrew/include/SDL2

CXX_FLAGSarm64 = -g -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.2 -Wall -Wcast-qual -Wdangling-else -Wnull-dereference -Wtype-limits -Wwrite-strings -Werror=bool-operation -Werror=int-to-pointer-cast -Werror=return-type -Werror=uninitialized -fsanitize=undefined -std=c++14

CXX_FLAGS = -g -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.2 -Wall -Wcast-qual -Wdangling-else -Wnull-dereference -Wtype-limits -Wwrite-strings -Werror=bool-operation -Werror=int-to-pointer-cast -Werror=return-type -Werror=uninitialized -fsanitize=undefined -std=c++14

